#Setup ~~~
#Follow these 2 steps to set up your site.

#Step 1: give your study group a name and a short description,
#and choose a language from the options in the _data directory:
title: CHICAS Spatial Statistics and Epidemiology Reading Group
description: "Reading Group"
language: en

#Step 2: press the green 'Commit Changes' button at the bottom of this page.

# That's it, your website is all set up!
# You can see it at https://YourUserName.github.io/studyGroup/
# No need to change anything below this line.
# To make your first event, check out the instructions at https://github.com/mozillascience/studyGroup#how-to-launch-a-new-event
# Having trouble? Open a new issue at https://github.com/mozillascience/studyGroup/issues and we'll help you out ASAP!

# Optional Configuration
# None of these things need to be changed - but feel free!

titleBackground: "img/5.jpg"
headlineSmall: "Welcome To Our Reading Group!"
headlineMain: "Let's Work Together"

# Setup Google Calendar
# Usage:
# 1. create a new google account; set the calendar to 'public' (see https://support.google.com/calendar/answer/37083?hl=en on how to do this)
# 2. change 'USER' in the example urls below to the username of the google account you made for your calendar
# 3. set calendar_on: True.

calendar_on: False
calendar_embed_url: "https://www.google.com/calendar/embed?src=USER@gmail.com"
calendar_ical_url: "https://www.google.com/calendar/ical/USER@gmail.com/public/basic.ics"


#========================================
# No touching anything below this line :)
#========================================
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: b5121b
  secondary: ea2e38
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
future: true
